enum MovieModes {
  onShore,
  oceanDiveSetup,
  oceanDive,
  backToOceanDive,
  backToTheDepthsSetup,
  suspendedAtSea,
  backToShore,
  backToTheDepths,
  toTheDepths,
  timesUp,
  // collaboratorPoolTimesUp,
  // individualPurpose,
  // purposeCallTimesUp,
  // enterThePurposeSessionDepths,
  // enterPhase3Depths,
}
