name: nokhte

packages:
  - packages/backend
  - packages/client

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  start-client:
    run: cd packages/client && flutter run --verbose
