name: primala_core


packages:
  - packages/client
  - packages/backend/dart


command:
  bootstrap:
    hooks:
      pre: dart run common_packs_injector.dart
    runPubGetInParallel: false
    usePubspecOverrides: true