name: nokhte

packages:
  - packages/backend
  - packages/client
  - packages/core

command:
  bootstrap:
    hooks:
      pre: dart run common_packs_injector.dart
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  start-client:
    run: cd packages/client && flutter run --verbose
