enum BeachWaveMovieModes {
  blackOut,
  blackOutToDrySand,
  oceanDiveToOnShore,
  oceanDiveToTimesUp,
  onShore,
  onShoreToOceanDiveSetup,
  onShoreToOceanDive,
  none,
  suspendedAtOceanDive,
  suspendedAtTheDepths,
  timesUp,
  timesUpDynamicPointToTheDepths,
  timesUpDynamicPointToTheDepthsSetup,
  timesUpEndToOceanDive,
  timesUpEndToTheDepths,
}
