enum BeachWaveMovieModes {
  none,
  onShoreToOceanDiveSetup,
  onShoreToOceanDive,
  oceanDiveToOnShore,
  onShore,
  blackOut,
  suspendedAtOceanDive,
  oceanDiveToTimesUp,
  timesUp,
  timesUpEndToOceanDive,
  timesUpEndToTheDepths,
  timesUpDynamicPointToTheDepths,
  timesUpDynamicPointToTheDepthsSetup,
  timesUpMovieStore,
  suspendedAtTheDepths,
}
