name: primala_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  # sdk: '>=2.19.6 <3.0.0'
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  dotenv: ^4.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  supabase_flutter: ^1.10.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
