// Mocks generated by Mockito 5.4.2 from annotations
// in nokhte/test/app/core/modules/local_speech_to_text/fixtures/local_speech_to_text_mock_gen.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i9;

import 'package:dartz/dartz.dart' as _i5;
import 'package:leopard_flutter/leopard.dart' as _i3;
import 'package:leopard_flutter/leopard_transcript.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nokhte/app/core/error/failure.dart' as _i11;
import 'package:nokhte/app/core/interfaces/logic.dart' as _i12;
import 'package:nokhte/app/core/modules/local_speech_to_text/constants/constants.dart'
    as _i10;
import 'package:nokhte/app/core/modules/local_speech_to_text/data/data.dart'
    as _i13;
import 'package:nokhte/app/core/modules/local_speech_to_text/domain/domain.dart'
    as _i2;
import 'package:nokhte/app/core/utilities/utilities.dart' as _i4;

import 'local_speech_to_text_mock_gen.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOnAudioRecorded_0 extends _i1.SmartFake
    implements _i2.OnAudioRecorded {
  _FakeOnAudioRecorded_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeopard_1 extends _i1.SmartFake implements _i3.Leopard {
  _FakeLeopard_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMicRecorder_2 extends _i1.SmartFake implements _i4.MicRecorder {
  _FakeMicRecorder_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalSpeechToTextContract_4 extends _i1.SmartFake
    implements _i2.LocalSpeechToTextContract {
  _FakeLocalSpeechToTextContract_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MLocalSpeechToTextRemoteSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMLocalSpeechToTextRemoteSourceImpl extends _i1.Mock
    implements _i6.MLocalSpeechToTextRemoteSourceImpl {
  MockMLocalSpeechToTextRemoteSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OnAudioRecorded get onAudioRecorded => (super.noSuchMethod(
        Invocation.getter(#onAudioRecorded),
        returnValue: _FakeOnAudioRecorded_0(
          this,
          Invocation.getter(#onAudioRecorded),
        ),
      ) as _i2.OnAudioRecorded);

  @override
  _i3.Leopard get leopard => (super.noSuchMethod(
        Invocation.getter(#leopard),
        returnValue: _FakeLeopard_1(
          this,
          Invocation.getter(#leopard),
        ),
      ) as _i3.Leopard);

  @override
  set leopard(_i3.Leopard? _leopard) => super.noSuchMethod(
        Invocation.setter(
          #leopard,
          _leopard,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.MicRecorder get micRecorder => (super.noSuchMethod(
        Invocation.getter(#micRecorder),
        returnValue: _FakeMicRecorder_2(
          this,
          Invocation.getter(#micRecorder),
        ),
      ) as _i4.MicRecorder);

  @override
  set micRecorder(_i4.MicRecorder? _micRecorder) => super.noSuchMethod(
        Invocation.setter(
          #micRecorder,
          _micRecorder,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> initLeopard() => (super.noSuchMethod(
        Invocation.method(
          #initLeopard,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i8.LeopardWord>> processAudio(_i9.File? recordedFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAudio,
          [recordedFile],
        ),
        returnValue:
            _i7.Future<List<_i8.LeopardWord>>.value(<_i8.LeopardWord>[]),
      ) as _i7.Future<List<_i8.LeopardWord>>);

  @override
  _i7.Future<List<_i8.LeopardWord>> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.LeopardWord>>.value(<_i8.LeopardWord>[]),
      ) as _i7.Future<List<_i8.LeopardWord>>);

  @override
  _i7.Future<_i10.SpeechToTextRecordingStatus> startRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i7.Future<_i10.SpeechToTextRecordingStatus>.value(
            _i10.SpeechToTextRecordingStatus.initial),
      ) as _i7.Future<_i10.SpeechToTextRecordingStatus>);
}

/// A class which mocks [MLocalSpeechToTextContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockMLocalSpeechToTextContract extends _i1.Mock
    implements _i6.MLocalSpeechToTextContract {
  MockMLocalSpeechToTextContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Either<_i11.Failure, _i2.SpeechToTextRecordingStatusEntity>>
      startRecording(_i12.NoParams? params) => (super.noSuchMethod(
            Invocation.method(
              #startRecording,
              [params],
            ),
            returnValue: _i7.Future<
                _i5.Either<_i11.Failure,
                    _i2.SpeechToTextRecordingStatusEntity>>.value(_FakeEither_3<
                _i11.Failure, _i2.SpeechToTextRecordingStatusEntity>(
              this,
              Invocation.method(
                #startRecording,
                [params],
              ),
            )),
          ) as _i7.Future<
              _i5.Either<_i11.Failure, _i2.SpeechToTextRecordingStatusEntity>>);

  @override
  _i7.Future<_i5.Either<_i11.Failure, _i2.AudioProcessingEntity>> stopRecording(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [params],
        ),
        returnValue: _i7
            .Future<_i5.Either<_i11.Failure, _i2.AudioProcessingEntity>>.value(
            _FakeEither_3<_i11.Failure, _i2.AudioProcessingEntity>(
          this,
          Invocation.method(
            #stopRecording,
            [params],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i11.Failure, _i2.AudioProcessingEntity>>);

  @override
  _i7.Future<_i5.Either<_i11.Failure, _i2.InitLeopardStatusEntity>> initLeopard(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #initLeopard,
          [params],
        ),
        returnValue: _i7.Future<
                _i5.Either<_i11.Failure, _i2.InitLeopardStatusEntity>>.value(
            _FakeEither_3<_i11.Failure, _i2.InitLeopardStatusEntity>(
          this,
          Invocation.method(
            #initLeopard,
            [params],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i11.Failure, _i2.InitLeopardStatusEntity>>);
}

/// A class which mocks [MInitLeopard].
///
/// See the documentation for Mockito's code generation for more information.
class MockMInitLeopard extends _i1.Mock implements _i6.MInitLeopard {
  MockMInitLeopard() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalSpeechToTextContract get contract => (super.noSuchMethod(
        Invocation.getter(#contract),
        returnValue: _FakeLocalSpeechToTextContract_4(
          this,
          Invocation.getter(#contract),
        ),
      ) as _i2.LocalSpeechToTextContract);

  @override
  _i7.Future<_i5.Either<_i11.Failure, _i2.InitLeopardStatusEntity>> call(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<
                _i5.Either<_i11.Failure, _i2.InitLeopardStatusEntity>>.value(
            _FakeEither_3<_i11.Failure, _i2.InitLeopardStatusEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i11.Failure, _i2.InitLeopardStatusEntity>>);
}

/// A class which mocks [MStopRecording].
///
/// See the documentation for Mockito's code generation for more information.
class MockMStopRecording extends _i1.Mock implements _i6.MStopRecording {
  MockMStopRecording() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalSpeechToTextContract get contract => (super.noSuchMethod(
        Invocation.getter(#contract),
        returnValue: _FakeLocalSpeechToTextContract_4(
          this,
          Invocation.getter(#contract),
        ),
      ) as _i2.LocalSpeechToTextContract);

  @override
  _i7.Future<_i5.Either<_i11.Failure, _i2.AudioProcessingEntity>> call(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7
            .Future<_i5.Either<_i11.Failure, _i2.AudioProcessingEntity>>.value(
            _FakeEither_3<_i11.Failure, _i2.AudioProcessingEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i11.Failure, _i2.AudioProcessingEntity>>);
}

/// A class which mocks [MStartRecording].
///
/// See the documentation for Mockito's code generation for more information.
class MockMStartRecording extends _i1.Mock implements _i6.MStartRecording {
  MockMStartRecording() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalSpeechToTextContract get contract => (super.noSuchMethod(
        Invocation.getter(#contract),
        returnValue: _FakeLocalSpeechToTextContract_4(
          this,
          Invocation.getter(#contract),
        ),
      ) as _i2.LocalSpeechToTextContract);

  @override
  _i7.Future<
      _i5.Either<_i11.Failure, _i2.SpeechToTextRecordingStatusEntity>> call(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<
                _i5.Either<_i11.Failure,
                    _i2.SpeechToTextRecordingStatusEntity>>.value(
            _FakeEither_3<_i11.Failure, _i2.SpeechToTextRecordingStatusEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<
          _i5.Either<_i11.Failure, _i2.SpeechToTextRecordingStatusEntity>>);
}

/// A class which mocks [LocalSpeechToTextRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalSpeechToTextRemoteSource extends _i1.Mock
    implements _i13.LocalSpeechToTextRemoteSource {
  @override
  _i7.Future<bool> initLeopard() => (super.noSuchMethod(
        Invocation.method(
          #initLeopard,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i8.LeopardWord>> processAudio(_i9.File? recordedFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAudio,
          [recordedFile],
        ),
        returnValue:
            _i7.Future<List<_i8.LeopardWord>>.value(<_i8.LeopardWord>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i8.LeopardWord>>.value(<_i8.LeopardWord>[]),
      ) as _i7.Future<List<_i8.LeopardWord>>);

  @override
  _i7.Future<List<_i8.LeopardWord>> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.LeopardWord>>.value(<_i8.LeopardWord>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i8.LeopardWord>>.value(<_i8.LeopardWord>[]),
      ) as _i7.Future<List<_i8.LeopardWord>>);

  @override
  _i7.Future<_i10.SpeechToTextRecordingStatus> startRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i7.Future<_i10.SpeechToTextRecordingStatus>.value(
            _i10.SpeechToTextRecordingStatus.initial),
        returnValueForMissingStub:
            _i7.Future<_i10.SpeechToTextRecordingStatus>.value(
                _i10.SpeechToTextRecordingStatus.initial),
      ) as _i7.Future<_i10.SpeechToTextRecordingStatus>);
}
