flutter test test/01_user_information_table_test.dart
flutter test test/01.5_user_information_table_test.dart
flutter test test/02_active_nokhte_sessions_pair_table_test.dart 
flutter test test/03_active_nokhte_sessions_triplet_table_test.dart 
flutter test test/04_active_nokhte_sessions_quintuplet_table_test.dart 
flutter test test/05_finished_nokhte_sessions_table_test.dart
flutter test test/06_active_monetization_sessions_table_test.dart