flutter test test/01_user_name_table_test.dart
flutter test test/02_collaborator_phrases_table_test.dart
flutter test test/03_synchronous_search_test.dart
flutter test test/04_fetch_agora_token_test.dart
flutter test test/05_existing_collaborations_table_test.dart
flutter test test/06_solo_p2p_purpose_documents_table_test.dart
flutter test test/07_finished_collaborative_p2p_purpose_documents_test.dart