flutter test test/01_user_names_table_test.dart
flutter test test/01.5_user_names_table_test.dart
flutter test test/02_get_agora_token_test.dart
flutter test test/03_synchronous_search_test.dart
flutter test test/04_active_nokhte_sessions_table_test.dart
flutter test test/05_nokhte_sessions_audio_bucket_test.dart
