enum Screens {
  login,
  homeRootRouter,
  compassAndStorageGuideHome,
  compassAndQrGuideHome,
  qrAndStorageAdeptHome,
  qrNavigationReminderHome,
  shortQrGuideHome,
  storageGuideHome,
  collaborationHome,
  collaboratorPool,
  nokhteSessionGreeter,
  nokhteSessionNotesInstructions,
  nokhteSessionNotes,
  nokhteSessionSpeakingInstructions,
  nokhteSessionSpeaking,
  nokhteSessionExit,
}
