name: backend-unit-tests
run-name: Backend Unit Tests
on:
  push:
    branches:
      - development
    paths:
      - "packages/backend/**"
  pull_request:
    branches:
      - development
    paths:
      - "packages/backend/**"


jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/backend
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: "stable"
      - uses: supabase/setup-cli@v1
      - shell: bash
        env: 
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
      - run: supabase start
      - run: supabase functions serve
      - run: cd dart && flutter test
