name: client-unit-tests
run-name: Client Unit Tests
on:
  push:
    paths:
      - 'packages/client/**'


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.13.9'
          channel: 'stable'
      - run: cd packages/client
      - run: flutter pub get
      - run: flutter test
