name: Client Android Staging Deploy
on:
  push:
    branches:
      - staging
    paths:
      - "packages/client/**"
  workflow_dispatch:

jobs:
  deploy:
    name: External Staging Deployment
    runs-on: macos-13
    defaults:
      run:
        working-directory: packages/client

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "11"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"
      - uses: bluefireteam/melos-action@v3
      - run: |
          echo "PROD_SUPABASE_URL='$STAGING_SUPABASE_URL'" >> .env
          echo "PROD_SUPABASE_ANON_KEY='$STAGING_SUPABASE_ANON_KEY'" >> .env
          echo "GLASSFY_STAGING_API_KEY='$GLASSFY_STAGING_API_KEY'" >> .env
          echo "GLASSFY_PROD_API_KEY='$GLASSFY_PROD_API_KEY'" >> .env
        env:
          APP_ID: ${{ secrets.PROD_APP_ID }}
          STAGING_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          STAGING_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
          GLASSFY_STAGING_API_KEY: ${{ secrets.GLASSFY_STAGING_API_KEY }}
          GLASSFY_PROD_API_KEY: ${{ secrets.GLASSFY_PROD_API_KEY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true
      - run: flutter pub run build_runner build
      - run: cd android && bundle install
      - run: |
          cd android 
          echo "$BASE_64_KEY_PROPERTIES" | base64 -d > key.properties
          echo "$BASE_64_UPLOAD_KEYSTORE" | base64 -d > primala-upload-key.keystore
          fastlane build
          fastlane internal_android_beta_build
        env:
          BASE_64_KEY_PROPERTIES: ${{secrets.BASE_64_KEY_PROPERTIES}}
          BASE_64_UPLOAD_KEYSTORE: ${{secrets.BASE_64_UPLOAD_KEYSTORE}}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_STORE_JSON_KEY_DATA}}
