name: Client Android Production Deploy
on:
  push:
    branches:
      - production
    paths:
      - "packages/client/**"
  workflow_dispatch:

jobs:
  deploy:
    name: External Staging Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/client

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: "stable"
      - uses: bluefireteam/melos-action@v3
      - run: |
          echo "PROD_SUPABASE_URL='$PROD_SUPABASE_URL'" >> .env
          echo "PROD_SUPABASE_ANON_KEY='$PROD_SUPABASE_ANON_KEY'" >> .env
          echo "AGORA_APP_ID='$AGORA_APP_ID'" >> .env
          echo "APP_ID='$APP_ID'" >> .env
        env:
          PROD_SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          PROD_SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
          APP_ID: ${{ secrets.PROD_APP_ID }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - run: flutter pub run build_runner build
      - run: cd android && bundle install
      - run: |
          cd android/app/src/main
          sed -i '' -e 's/android:name="io.branch.sdk.TestMode" android:value="true"/android:name="io.branch.sdk.TestMode" android:value="false"/' AndroidManifest.xml
          cd ../../..
          echo "$BASE_64_KEY_PROPERTIES" | base64 -d > key.properties
          echo "$BASE_64_UPLOAD_KEYSTORE" | base64 -d > primala-upload-key.keystore
          fastlane build
          fastlane external_android_beta_build
        env:
          BASE_64_KEY_PROPERTIES: ${{secrets.BASE_64_KEY_PROPERTIES}}
          BASE_64_UPLOAD_KEYSTORE: ${{secrets.BASE_64_UPLOAD_KEYSTORE}}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_STORE_JSON_KEY_DATA}}
