name: client-unit-tests
run-name: Client Unit Tests
on:
  push:
    branches:
      - development
    paths:
      - "packages/client/**"
  pull_request:
    branches:
      - development
    paths:
      - "packages/client/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/client
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: "stable"
      - run: touch .env
      - run: flutter pub get
      - run: flutter test
