name: Client Staging iOS Deploy
on:
  push:
    branches:
      - staging
    paths:
      - "packages/client/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/client
    env:
      STAGING_CLIENT_ENV: ${{ secrets.STAGING_CLIENT_ENV }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: "stable"
      - uses: bluefireteam/melos-action@v3
      - run: echo '$STAGING_CLIENT_ENV' > .env
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' 
          bundler-cache: true
      - run: cd ios && bundle install
      - run: cd ios && fastlane rebuild_ios_archive
        env:
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            MATCH_BASIC_GIT_AUTHORIZATION: ${{ secrets.MATCH_BASIC_GIT_AUTHORIZATION }}
      - run: cd ios && fastlane generic_ios_beta_build
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: ${{secrets.APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64}}

